"""SLCV32-RZ Relative Quality Engine Candidate Q1."""

CANDIDATE = "SLCV32-RZ RELATIVE QUALITY ENGINE CANDIDATE Q1"
PREDECESSOR = "SLCV31-RZ QUALITY ENGINE CANDIDATE E1"
CURRENT_SLC = "SLCV21R"
PROMOTED = False

__all__ = ["CANDIDATE", "CURRENT_SLC", "PREDECESSOR", "PROMOTED"]
