"""CR220 native 63 generator.

Build target from SAM_NEXT_MOVES_NATIVE_RESET.md:
generate the first Tier 1 product, Tier1_Native63.csv, from locked SAM
constants only.  CR219 is used downstream as a validation surface only; no
candidate IDs, labels, names, or imported rows are construction inputs.
"""
from __future__ import annotations

import csv
import hashlib
import json
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from decimal import Decimal, getcontext
from fractions import Fraction
from pathlib import Path
from typing import Iterable


getcontext().prec = 80

CR_ID = "CR220"
TEST_ID = "CR220_NATIVE_63_GENERATOR"

CR_DIR = Path(__file__).resolve().parent
BRANCH_DIR = CR_DIR.parent
COURTROOM_DIR = BRANCH_DIR.parent

ROADMAP = BRANCH_DIR / "SAM_NEXT_MOVES_NATIVE_RESET.md"
CR219_PROMOTED = (
    COURTROOM_DIR
    / "09a_PARTICLE_MASS_CHAIN"
    / "CR219_PROMOTED_PARTICLE_ROWS_EXPORT"
    / "CR219_promoted_particle_rows_126.csv"
)

OUT_NATIVE = CR_DIR / "Tier1_Native63.csv"
OUT_VALIDATION_SOURCE = CR_DIR / "CR220_downstream_validation_CR219_stable63.csv"
OUT_VALIDATION = CR_DIR / "CR220_validation_against_CR219.csv"
OUT_CHECKS = CR_DIR / "CR220_checks.csv"
OUT_PRECOMMIT = CR_DIR / "CR220_PRECOMMIT.md"
OUT_SUMMARY = CR_DIR / "CR220_summary.json"
OUT_RESULT = CR_DIR / "CR220_result.md"
OUT_README = CR_DIR / "README.md"
OUT_HASHES = CR_DIR / "HASHES.txt"

ALPHA_H = 2
D = 3
R = 12
PARTITION_MODES = (1, 2, 3, 4, 6, 8, 9, 12)
DEPTH_PARTITIONS = {
    0: PARTITION_MODES,
    1: PARTITION_MODES,
    2: (1, 2, 3, 4, 6),
}

# Row Order V1 locks the organized visible triplet order as neutral, positive,
# negative.  Validation against CR219 is by address signature, not imported ID.
CHARGE_STATES = (
    ("neutral", 0, "OUTER_BINARY_NEUTRAL", "outer_binary_neutral", Fraction(1, 8)),
    ("positive", 1, "V4_1_SINGLE_WRITE", "single_write", Fraction(5, 4)),
    ("negative", -1, "V4_1_SINGLE_WRITE", "single_write", Fraction(3, 2)),
)

CSV_FIELDS = [
    "native_id",
    "partition_mode",
    "generator_exponents",
    "generator_exponent_alphaH",
    "generator_exponent_D",
    "depth",
    "charge_sign",
    "charge_magnitude",
    "native_charge_axis",
    "operator_class",
    "route_class",
    "native_mass_or_weight",
    "native_mass_fraction",
    "source_support",
    "source_support_decimal",
    "tensor_support",
    "tensor_support_decimal",
    "retained_support",
    "retained_support_decimal",
    "selector_rule",
    "address_signature",
    "route_combination",
    "construction_hash",
]


@dataclass(frozen=True)
class Check:
    check: str
    passed: bool
    observed: str
    expected: str


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_json(path: Path, obj: object) -> None:
    path.write_text(json.dumps(obj, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def fraction_text(value: Fraction) -> str:
    if value.denominator == 1:
        return str(value.numerator)
    return f"{value.numerator}/{value.denominator}"


def decimal_text(value: Fraction, places: int = 48) -> str:
    dec = Decimal(value.numerator) / Decimal(value.denominator)
    s = format(dec, f".{places}f")
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s or "0"


def exponents_for_partition(p: int) -> tuple[int, int]:
    n = p
    a = 0
    while n % ALPHA_H == 0:
        a += 1
        n //= ALPHA_H
    b = 0
    while n % D == 0:
        b += 1
        n //= D
    if n != 1:
        raise ValueError(f"partition {p} is not generated by alpha_H={ALPHA_H} and D={D}")
    return a, b


def selector_rule_for(p: int, depth: int) -> str:
    if depth in (0, 1):
        return "DEPTH_0_1_ALL_PARTITION_MODES"
    if depth == 2 and p in DEPTH_PARTITIONS[2]:
        return "DEPTH_2_LOW_PARTITION_MODES_ONLY"
    return "FORBIDDEN_BY_NATIVE_SELECTOR"


def row_hash(payload: dict[str, str]) -> str:
    keys = [
        "partition_mode",
        "generator_exponents",
        "depth",
        "charge_sign",
        "charge_magnitude",
        "operator_class",
        "native_mass_fraction",
        "source_support",
        "tensor_support",
        "retained_support",
        "selector_rule",
    ]
    material = {
        "constants": {"alpha_H": ALPHA_H, "D": D, "R": R},
        "row": {k: payload[k] for k in keys},
        "generator": TEST_ID,
    }
    return hashlib.sha256(json.dumps(material, sort_keys=True).encode("utf-8")).hexdigest()


def build_native_rows(
    depth_partitions: dict[int, tuple[int, ...]] | None = None,
    charge_states: tuple[tuple[str, int, str, str, Fraction], ...] = CHARGE_STATES,
) -> list[dict[str, str]]:
    depth_partitions = depth_partitions or DEPTH_PARTITIONS
    rows: list[dict[str, str]] = []
    ordinal = 1
    for depth in sorted(depth_partitions):
        for p in depth_partitions[depth]:
            a, b = exponents_for_partition(p)
            for charge_sign, charge_int, operator_class, route_class, mass_factor in charge_states:
                mass = Fraction(p, 1) * (R ** depth) * mass_factor
                charge_magnitude = 0 if charge_sign == "neutral" else p
                if charge_sign == "neutral":
                    source = mass
                else:
                    source = mass * Fraction(R * R + 1, R * R)
                tensor = source / (2 ** D)
                retained = source - tensor
                row = {
                    "native_id": f"SAMN63-{ordinal:04d}",
                    "partition_mode": str(p),
                    "generator_exponents": f"alpha_H^{a}*D^{b}",
                    "generator_exponent_alphaH": str(a),
                    "generator_exponent_D": str(b),
                    "depth": str(depth),
                    "charge_sign": charge_sign,
                    "charge_magnitude": str(charge_magnitude),
                    "native_charge_axis": {
                        "neutral": "neutral",
                        "positive": "plus",
                        "negative": "minus",
                    }[charge_sign],
                    "operator_class": operator_class,
                    "route_class": route_class,
                    "native_mass_or_weight": decimal_text(mass, places=24),
                    "native_mass_fraction": fraction_text(mass),
                    "source_support": fraction_text(source),
                    "source_support_decimal": decimal_text(source),
                    "tensor_support": fraction_text(tensor),
                    "tensor_support_decimal": decimal_text(tensor),
                    "retained_support": fraction_text(retained),
                    "retained_support_decimal": decimal_text(retained),
                    "selector_rule": selector_rule_for(p, depth),
                    "address_signature": f"p={p}|d={depth}|q={charge_sign}:{charge_magnitude}",
                    "route_combination": f"{charge_sign}_single_write[p={p},g={depth}]",
                    "construction_hash": "",
                }
                row["construction_hash"] = row_hash(row)
                rows.append(row)
                ordinal += 1
    return rows


def render_csv(rows: Iterable[dict[str, str]], fields: list[str]) -> bytes:
    from io import StringIO

    buf = StringIO()
    writer = csv.DictWriter(buf, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({field: row.get(field, "") for field in fields})
    return buf.getvalue().encode("utf-8")


def write_csv(path: Path, rows: Iterable[dict[str, str]], fields: list[str]) -> None:
    path.write_bytes(render_csv(rows, fields))


def address_key(row: dict[str, str]) -> tuple[int, int, str]:
    return (int(row["partition_mode"]), int(row["depth"]), row["charge_sign"])


def cr219_address_key(row: dict[str, str]) -> tuple[int, int, str]:
    return (
        int(row["partition_signature"]),
        int(row["closure_depth"]),
        row["q_sign"],
    )


def read_cr219_stable_rows() -> list[dict[str, str]]:
    with CR219_PROMOTED.open("r", encoding="utf-8", newline="") as f:
        rows = [
            row for row in csv.DictReader(f)
            if row.get("bin") == "stable_matter_rows"
        ]
    return rows


def validation_rows(native_rows: list[dict[str, str]], cr219_rows: list[dict[str, str]]) -> list[dict[str, str]]:
    generated = {address_key(row): row for row in native_rows}
    source = {cr219_address_key(row): row for row in cr219_rows}
    all_keys = sorted(set(generated) | set(source))
    rows = []
    for key in all_keys:
        g = generated.get(key)
        s = source.get(key)
        generated_mass = Fraction(g["native_mass_fraction"]) if g else None
        source_mass = Fraction(s["M_native"]) if s else None
        operator_match = bool(g and s and g["operator_class"] == s["operator_class"])
        mass_match = bool(g and s and generated_mass == source_mass)
        rows.append({
            "partition_mode": str(key[0]),
            "depth": str(key[1]),
            "charge_sign": key[2],
            "generated_native_id": g["native_id"] if g else "",
            "cr219_candidate_id": s["candidate_id"] if s else "",
            "signature_in_generated": str(g is not None),
            "signature_in_cr219": str(s is not None),
            "operator_match": str(operator_match),
            "native_mass_match": str(mass_match),
            "generated_operator_class": g["operator_class"] if g else "",
            "cr219_operator_class": s["operator_class"] if s else "",
            "generated_native_mass_fraction": g["native_mass_fraction"] if g else "",
            "cr219_M_native": s["M_native"] if s else "",
            "used_as_construction_input": "no",
        })
    return rows


def check_duplicate_repair_failure(rows: list[dict[str, str]]) -> bool:
    repaired = [dict(r) for r in rows]
    repaired[0] = dict(repaired[1])
    keys = [(r["partition_mode"], r["depth"], r["charge_sign"]) for r in repaired]
    return len(repaired) == 63 and len(set(keys)) != 63


def build_checks(native_rows: list[dict[str, str]], validation: list[dict[str, str]]) -> list[Check]:
    depth_counts: dict[str, int] = {}
    for row in native_rows:
        depth_counts[row["depth"]] = depth_counts.get(row["depth"], 0) + 1
    address_keys = [(r["partition_mode"], r["depth"], r["charge_sign"]) for r in native_rows]
    forbidden_d2 = [
        r["partition_mode"] for r in native_rows
        if r["depth"] == "2" and r["partition_mode"] in {"8", "9", "12"}
    ]
    labels_present = [
        key for row in native_rows
        for key, value in row.items()
        if key in {"known_name", "known_symbol", "known_label", "candidate_id"} and value
    ]
    all_validation_matches = all(
        row["signature_in_generated"] == "True"
        and row["signature_in_cr219"] == "True"
        and row["operator_match"] == "True"
        and row["native_mass_match"] == "True"
        for row in validation
    )
    full_depth2 = dict(DEPTH_PARTITIONS)
    full_depth2[2] = PARTITION_MODES
    wrong_72 = build_native_rows(depth_partitions=full_depth2)
    wrong_two_charges = build_native_rows(charge_states=CHARGE_STATES[:2])
    rendered_1 = render_csv(native_rows, CSV_FIELDS)
    rendered_2 = render_csv(build_native_rows(), CSV_FIELDS)

    return [
        Check("native_rows_exactly_63", len(native_rows) == 63, str(len(native_rows)), "63"),
        Check("depth_counts_24_24_15", depth_counts == {"0": 24, "1": 24, "2": 15}, str(depth_counts), "{'0': 24, '1': 24, '2': 15}"),
        Check("addresses_unique_63", len(set(address_keys)) == 63, str(len(set(address_keys))), "63"),
        Check("forbidden_depth2_modes_absent", not forbidden_d2, ",".join(forbidden_d2), "none"),
        Check("known_labels_absent_from_construction_fields", not labels_present, str(labels_present), "[]"),
        Check("deterministic_byte_identical_regeneration", rendered_1 == rendered_2, sha256_bytes(rendered_1), sha256_bytes(rendered_2)),
        Check("wrong_control_depth2_full_modes_produces_72", len(wrong_72) == 72, str(len(wrong_72)), "72"),
        Check("wrong_control_removed_charge_state_breaks_count", len(wrong_two_charges) != 63, str(len(wrong_two_charges)), "not 63"),
        Check("wrong_control_duplicate_repair_fails_uniqueness", check_duplicate_repair_failure(native_rows), "duplicate_repaired_count_63_unique_lt_63", "detected"),
        Check("downstream_cr219_validation_63_signatures_mass_operator", all_validation_matches, str(sum(1 for row in validation if row['native_mass_match'] == 'True')), "63"),
    ]


def write_hashes(paths: list[Path]) -> None:
    lines = []
    for path in sorted(paths, key=lambda p: p.name):
        lines.append(f"{sha256_file(path)}  {path.name}")
    OUT_HASHES.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_precommit(native_rows_sha: str) -> None:
    text = f"""# CR220 PRECOMMIT - Native 63 Generator

## Scope

Generate `Tier1_Native63.csv` from SAM constants only:

```text
alpha_H = {ALPHA_H}
D = {D}
R = {R}
Pi = {PARTITION_MODES}
charges = neutral, positive, negative
```

## Generator

Depths 0 and 1 admit all eight partition modes. Depth 2 admits only
`1, 2, 3, 4, 6`. For every allowed `(p,d)`, emit the neutral, positive,
negative triplet.

Native mass:

```text
M_native = p * R^d * k
neutral  k = 1/8
positive k = 5/4
negative k = 3/2
```

Charged source support uses the first carrier lift:

```text
source_support(charged) = M_native * (R^2 + 1) / R^2
source_support(neutral) = M_native
tensor_support          = source_support / 2^D
retained_support        = source_support - tensor_support
```

## Source Boundary

`CR219_promoted_particle_rows_126.csv` is read only after generation as a
downstream validation surface. It supplies no candidate IDs, names, labels, or
rows to the construction step.

## Pre-run Hash

Expected generated CSV hash after deterministic construction:

```text
{native_rows_sha}
```
"""
    OUT_PRECOMMIT.write_text(text, encoding="utf-8")


def write_readme() -> None:
    text = f"""# CR220 Native 63 Generator

This artifact implements the first milestone from
`SAM_NEXT_MOVES_NATIVE_RESET.md`: generate the native single-write 63 from
SAM constants only.

Primary product:

```text
Tier1_Native63.csv
```

CR219 is used only for downstream validation in
`CR220_validation_against_CR219.csv`.
"""
    OUT_README.write_text(text, encoding="utf-8")


def write_result(summary: dict[str, object]) -> None:
    result_class = summary["result_class"]
    checks_passed = summary["checks_passed"]
    checks_total = summary["checks_total"]
    text = f"""# CR220 Native 63 Generator Result

**Result class:** `{result_class}`

**Checks:** {checks_passed}/{checks_total}

## Verdict

The native Tier 1 single-write surface is generated from constants only as
`24 + 24 + 15 = 63`. No known names, symbols, candidate IDs, or external labels
enter construction. CR219 is used only after generation to confirm that the
native address signatures, operator classes, and native masses match the
existing promoted stable-matter rows.

## Outputs

- `Tier1_Native63.csv`
- `CR220_downstream_validation_CR219_stable63.csv`
- `CR220_validation_against_CR219.csv`
- `CR220_checks.csv`
- `CR220_summary.json`
- `HASHES.txt`

## Next Gate

CR221 should generate the true bound 63 from closure operators, not by mirroring
this native 63.
"""
    OUT_RESULT.write_text(text, encoding="utf-8")


def main() -> int:
    CR_DIR.mkdir(parents=True, exist_ok=True)

    native_rows = build_native_rows()
    native_csv_bytes = render_csv(native_rows, CSV_FIELDS)
    native_sha = sha256_bytes(native_csv_bytes)
    OUT_NATIVE.write_bytes(native_csv_bytes)

    cr219_rows = read_cr219_stable_rows()
    validation_source_fields = [
        "candidate_id",
        "bin",
        "route_combination",
        "operator_class",
        "partition_signature",
        "closure_depth",
        "q_sign",
        "q_abs",
        "M_native",
        "known_identity_label",
        "known_symbol",
        "known_name",
        "known_label_used_as_construction_input",
    ]
    write_csv(OUT_VALIDATION_SOURCE, cr219_rows, validation_source_fields)

    validation = validation_rows(native_rows, cr219_rows)
    validation_fields = [
        "partition_mode",
        "depth",
        "charge_sign",
        "generated_native_id",
        "cr219_candidate_id",
        "signature_in_generated",
        "signature_in_cr219",
        "operator_match",
        "native_mass_match",
        "generated_operator_class",
        "cr219_operator_class",
        "generated_native_mass_fraction",
        "cr219_M_native",
        "used_as_construction_input",
    ]
    write_csv(OUT_VALIDATION, validation, validation_fields)

    checks = build_checks(native_rows, validation)
    write_csv(OUT_CHECKS, [asdict(check) for check in checks], ["check", "passed", "observed", "expected"])

    checks_passed = sum(1 for check in checks if check.passed)
    checks_total = len(checks)
    result_class = (
        "CR220_PASS_NATIVE_63_GENERATOR__CONSTANTS_ONLY__24_24_15__"
        "DOWNSTREAM_CR219_SIGNATURE_MATCH"
        if checks_passed == checks_total
        else "CR220_FAIL_NATIVE_63_GENERATOR"
    )

    summary = {
        "cr_id": CR_ID,
        "test_id": TEST_ID,
        "execution_status": "CLEAN",
        "generated_at_utc": now_utc(),
        "result_class": result_class,
        "checks_passed": checks_passed,
        "checks_total": checks_total,
        "constants": {"alpha_H": ALPHA_H, "D": D, "R": R},
        "partition_modes": list(PARTITION_MODES),
        "depth_partitions": {str(k): list(v) for k, v in DEPTH_PARTITIONS.items()},
        "charge_order": [c[0] for c in CHARGE_STATES],
        "row_count": len(native_rows),
        "depth_counts": {
            str(depth): sum(1 for row in native_rows if row["depth"] == str(depth))
            for depth in sorted(DEPTH_PARTITIONS)
        },
        "source_boundary": "CR219 read after generation as downstream validation only; no imported IDs or labels in construction.",
        "roadmap": str(ROADMAP.relative_to(COURTROOM_DIR)),
        "validation_source": str(CR219_PROMOTED.relative_to(COURTROOM_DIR)),
        "outputs": {
            "native_csv": OUT_NATIVE.name,
            "validation_source_csv": OUT_VALIDATION_SOURCE.name,
            "validation_csv": OUT_VALIDATION.name,
            "checks_csv": OUT_CHECKS.name,
            "summary_json": OUT_SUMMARY.name,
            "result_md": OUT_RESULT.name,
        },
        "sha256": {
            "Tier1_Native63.csv": native_sha,
        },
        "next_gate": "CR221_BOUND_63_GENERATOR",
    }

    write_precommit(native_sha)
    write_readme()
    write_json(OUT_SUMMARY, summary)
    write_result(summary)
    write_hashes([
        OUT_NATIVE,
        OUT_VALIDATION_SOURCE,
        OUT_VALIDATION,
        OUT_CHECKS,
        OUT_PRECOMMIT,
        OUT_SUMMARY,
        OUT_RESULT,
        OUT_README,
    ])

    print("CR220 native 63 generator complete")
    print(f"  result_class: {result_class}")
    print(f"  checks: {checks_passed}/{checks_total}")
    print(f"  rows: {len(native_rows)}")
    print(f"  Tier1_Native63.csv sha256: {native_sha}")
    return 0 if checks_passed == checks_total else 1


if __name__ == "__main__":
    raise SystemExit(main())
