#pragma once
#include "engine.hpp"
#include <functional>
#include <numeric>

namespace source_algebra {
using rxt::need;
inline long D=0;
inline unsigned long assertions=0;
inline void ck(bool v,const std::string&s){++assertions;need(v,s);}
struct F {
 mpq_class a=0,b=0;
 F()=default; F(long x):a(x){} F(mpq_class x):a(x){} F(mpq_class x,mpq_class y):a(x),b(y){}
 bool zero()const{return a==0&&b==0;}
 F operator-()const{return F(-a,-b);}
 F operator+(const F&v)const{return F(a+v.a,b+v.b);}
 F operator-(const F&v)const{return F(a-v.a,b-v.b);}
 F operator*(const F&v)const{return F(a*v.a+D*b*v.b,a*v.b+b*v.a);}
 F operator/(const F&v)const{mpq_class n=v.a*v.a-D*v.b*v.b;ck(n!=0,"Division by zero in exact field");return F((a*v.a-D*b*v.b)/n,(b*v.a-a*v.b)/n);}
 F&operator+=(const F&v){return *this=*this+v;} F&operator-=(const F&v){return *this=*this-v;} F&operator*=(const F&v){return *this=*this*v;}
 bool operator==(const F&v)const{return a==v.a&&b==v.b;} bool operator!=(const F&v)const{return !(*this==v);}
};
inline F scalar(const json&v){if(v.is_object()){ck(D!=0&&v.size()==2&&v.contains("a")&&v.contains("b"),"Quadratic scalar requires a,b and a declared field");return F(rxt::rational(v.at("a")),rxt::rational(v.at("b")));}return F(rxt::rational(v));}
inline json dump(const F&x){if(x.b==0)return rxt::number(x.a);return json{{"a",rxt::number(x.a)},{"b",rxt::number(x.b)}};}
inline void field(const json&p){D=0;assertions=0;auto f=p.at("field");ck(f.is_object()&&f.size()==1&&f.contains("radicand")&&f["radicand"].is_number_integer(),"Field needs an integer radicand");D=f["radicand"].get<long>();ck(D==0||(D>=2&&D<=1000000&&!mpz_perfect_square_p(mpz_class(D).get_mpz_t())),"Admit Q or a real nonsquare quadratic field");}
using M=std::vector<std::vector<F>>;using PM=std::vector<M>;
inline M z(size_t n,size_t m){return M(n,std::vector<F>(m));}
inline size_t cols(const M&a){return a.empty()?0:a[0].size();}
inline M eye(size_t n){auto a=z(n,n);for(size_t i=0;i<n;i++)a[i][i]=1;return a;}
inline M read(const json&j,size_t maxrows=64,size_t maxcols=64){ck(j.is_array()&&!j.empty()&&j.size()<=maxrows&&j[0].is_array()&&!j[0].empty()&&j[0].size()<=maxcols,"Matrix outside admitted dimensions");auto a=z(j.size(),j[0].size());for(size_t i=0;i<a.size();i++){ck(j[i].is_array()&&j[i].size()==cols(a),"Ragged matrix");for(size_t k=0;k<cols(a);k++)a[i][k]=scalar(j[i][k]);}return a;}
inline json dump(const M&a){json out=json::array();for(auto&r:a){json row=json::array();for(auto&v:r)row.push_back(dump(v));out.push_back(row);}return out;}
inline M tr(const M&a){auto b=z(cols(a),a.size());for(size_t i=0;i<a.size();i++)for(size_t j=0;j<cols(a);j++)b[j][i]=a[i][j];return b;}
inline M add(M a,const M&b,int sign=1){ck(a.size()==b.size()&&cols(a)==cols(b),"Addition shape differs");for(size_t i=0;i<a.size();i++)for(size_t j=0;j<cols(a);j++)a[i][j]+=sign==1?b[i][j]:-b[i][j];return a;}
inline M scale(M a,const F&f){for(auto&r:a)for(auto&v:r)v*=f;return a;}
inline M mul(const M&a,const M&b){ck(cols(a)==b.size(),"Multiplication shape differs");auto c=z(a.size(),cols(b));for(size_t i=0;i<a.size();i++)for(size_t k=0;k<b.size();k++)if(!a[i][k].zero())for(size_t j=0;j<cols(b);j++)if(!b[k][j].zero())c[i][j]+=a[i][k]*b[k][j];return c;}
inline M kron(const M&a,const M&b){ck(a.size()*b.size()<=64&&cols(a)*cols(b)<=64,"Tensor dimension exceeds64");auto c=z(a.size()*b.size(),cols(a)*cols(b));for(size_t i=0;i<a.size();i++)for(size_t j=0;j<cols(a);j++)for(size_t k=0;k<b.size();k++)for(size_t l=0;l<cols(b);l++)c[i*b.size()+k][j*cols(b)+l]=a[i][j]*b[k][l];return c;}
inline bool zero(const M&a){for(auto&r:a)for(auto&v:r)if(!v.zero())return false;return true;}
inline bool equal(const M&a,const M&b){return a==b;}
inline void eq(const M&a,const M&b,const std::string&s){ck(equal(a,b),s);}
struct RR{M a;std::vector<int>pivots;};
inline RR rref(M a,size_t pivotlimit=0){if(!pivotlimit)pivotlimit=cols(a);size_t row=0;std::vector<int>pivots;for(size_t col=0;col<pivotlimit&&row<a.size();col++){size_t k=row;while(k<a.size()&&a[k][col].zero())k++;if(k==a.size())continue;std::swap(a[k],a[row]);F d=a[row][col];for(size_t j=col;j<cols(a);j++)a[row][j]=a[row][j]/d;for(size_t i=0;i<a.size();i++)if(i!=row&&!a[i][col].zero()){F t=a[i][col];for(size_t j=col;j<cols(a);j++)a[i][j]-=t*a[row][j];}pivots.push_back(col);row++;}return {a,pivots};}
inline M inverse(M a){ck(a.size()==cols(a),"Inverse needs square matrix");auto n=a.size();for(size_t i=0;i<n;i++)for(size_t j=0;j<n;j++)a[i].push_back(F(i==j?1:0));auto r=rref(a,n);ck(r.pivots.size()==n,"Singular matrix");auto b=z(n,n);for(size_t i=0;i<n;i++)for(size_t j=0;j<n;j++)b[i][j]=r.a[i][n+j];return b;}
inline M selected(const M&a,const std::vector<int>&pivots){auto b=z(a.size(),pivots.size());for(size_t i=0;i<a.size();i++)for(size_t j=0;j<pivots.size();j++)b[i][j]=a[i][pivots[j]];return b;}
inline M independent(const M&a){return selected(a,rref(a).pivots);}
inline M nullspace(const RR&r){size_t n=cols(r.a);auto b=z(n,n-r.pivots.size());size_t c=0;for(size_t j=0;j<n;j++)if(std::find(r.pivots.begin(),r.pivots.end(),j)==r.pivots.end()){b[j][c]=1;for(size_t k=0;k<r.pivots.size();k++)b[r.pivots[k]][c]=-r.a[k][j];c++;}return b;}
inline M join(M a,const M&b){ck(a.size()==b.size(),"Column join shape");for(size_t i=0;i<a.size();i++)a[i].insert(a[i].end(),b[i].begin(),b[i].end());return a;}
inline M stack(const std::vector<M>&a){M v;for(auto&m:a)v.insert(v.end(),m.begin(),m.end());return v;}
inline M comm(const M&a,const M&b){return add(mul(a,b),mul(b,a),-1);}
inline M eval(const PM&p,const F&x){auto a=z(p[0].size(),cols(p[0]));for(auto it=p.rbegin();it!=p.rend();++it)a=add(scale(a,x),*it);return a;}
inline PM polyread(const json&a){ck(a.is_array()&&!a.empty()&&a.size()<=65,"Polynomial degree exceeds64");PM p;for(auto&v:a)p.push_back(read(v));for(auto&m:p)ck(m.size()==p[0].size()&&cols(m)==cols(p[0]),"Polynomial coefficient shape");return p;}
inline json polydump(const PM&p){json a=json::array();for(auto&m:p)a.push_back(dump(m));return a;}
inline M hamiltonian(const json&p){auto h=read(p.at("H"));ck(h.size()==cols(h),"Hamiltonian must be square");eq(h,tr(h),"Exact real self-adjoint Hamiltonian required");return h;}
inline void reference(const M&h,const M&v,const F&e){ck(v.size()==h.size()&&cols(v)==1&&!zero(v),"Nonzero compatible reference required");eq(mul(h,v),scale(v,e),"Reference is not an eigenstate at the supplied energy");}

inline json words(const json&p){std::map<std::string,M>vars;auto symbols=p.at("operators");ck(symbols.is_object()&&symbols.size()<=64,"At most64 source operators");for(auto it=symbols.begin();it!=symbols.end();++it)vars[it.key()]=read(it.value());auto program=p.at("program");ck(program.is_array()&&!program.empty()&&program.size()<=256,"Program needs1..256 ordered steps");json history=json::array();for(auto&step:program){auto name=step.at("name").get<std::string>(),op=step.at("op").get<std::string>();ck(!name.empty()&&!vars.count(name),"Word names are immutable and distinct");std::vector<M>args;if(step.contains("inputs"))for(auto&i:step["inputs"]){auto key=i.get<std::string>();ck(vars.count(key),"Unknown word input");args.push_back(vars.at(key));}M value;if(op=="identity"){auto n=step.at("dimension").get<int>();ck(n>=1&&n<=64,"Identity dimension1..64");value=eye(n);}else if(op=="multiply"||op=="add"||op=="columns"){ck(args.size()>=2,"At least two ordered inputs required");value=args[0];for(size_t i=1;i<args.size();i++)value=op=="multiply"?mul(value,args[i]):op=="columns"?join(value,args[i]):add(value,args[i]);}else if(op=="scale"){ck(args.size()==1,"Scale needs one input");value=scale(args[0],scalar(step.at("factor")));}else if(op=="transpose"){ck(args.size()==1,"Transpose needs one input");value=tr(args[0]);}else if(op=="commutator"||op=="subtract"||op=="tensor"){ck(args.size()==2,"Binary operation needs two inputs");value=op=="commutator"?comm(args[0],args[1]):op=="subtract"?add(args[0],args[1],-1):kron(args[0],args[1]);}else throw std::invalid_argument("Unknown source word operation");ck(value.size()<=64&&cols(value)<=64,"Word dimensions exceed64");vars[name]=value;history.push_back(step);}auto key=p.at("output").get<std::string>();ck(vars.count(key),"Unknown output word");return {{"matrix",dump(vars[key])},{"ordered_program",history},{"output",key},{"rank",rref(vars[key]).pivots.size()}};}

inline json subspace(const json&p){auto H=hamiltonian(p),seeds=read(p.at("seeds"));ck(seeds.size()==H.size(),"Source seed dimension differs");auto basis=independent(seeds);ck(cols(basis)>0,"Seed rank must be positive");auto mode=p.at("mode").get<std::string>();ck(mode=="ADMIT"||mode=="CLOSURE","Unknown subspace mode");json growth=json::array({cols(basis)});if(mode=="CLOSURE")while(cols(basis)<H.size()){auto next=independent(join(basis,mul(H,basis)));if(cols(next)==cols(basis))break;basis=next;growth.push_back(cols(basis));}auto G=mul(tr(basis),basis),K=mul(inverse(G),mul(tr(basis),mul(H,basis)));auto residual=add(mul(H,basis),mul(basis,K),-1);json out={{"basis",dump(basis)},{"Gram",dump(G)},{"compressed_H",dump(K)},{"residual",dump(residual)},{"rank",cols(basis)},{"growth",growth},{"invariant",zero(residual)},{"nonleaking_coefficients",dump(nullspace(rref(residual)))}};if(p.contains("reference")){auto v=read(p["reference"]);auto e=scalar(p.at("reference_energy"));reference(H,v,e);out["reference_eigenstate_verified"]=true;}return out;}

struct Rec {M H;std::vector<M>Q,G,A,B;std::vector<PM>Fpoly;M terminal;bool closed=false;};
inline Rec recurrence_data(const M&H,const M&seed,int limit){ck(seed.size()==H.size()&&cols(seed)>=1&&cols(seed)<=8,"Compatible seed block width1..8 required");ck(rref(seed).pivots.size()==cols(seed),"Initial seed block must have full column rank");Rec r;r.H=H;auto current=seed;auto k=cols(seed);PM prev,cur={eye(k)};r.Fpoly.push_back(cur);for(int n=0;n<limit;n++){auto gram=mul(tr(current),current);if(rref(gram).pivots.size()!=k){r.terminal=current;break;}auto A=mul(inverse(gram),mul(tr(current),mul(H,current)));M B=n?mul(inverse(r.G.back()),gram):z(k,k);for(auto&old:r.Q)eq(mul(tr(old),current),z(k,k),"Block orthogonality");eq(mul(gram,A),mul(tr(A),gram),"Gram adjoint");auto next=add(mul(H,current),mul(current,A),-1);if(n)next=add(next,mul(r.Q.back(),B),-1);r.Q.push_back(current);r.G.push_back(gram);r.A.push_back(A);r.B.push_back(B);PM poly(cur.size()+1,z(k,k));for(size_t j=0;j<cur.size();j++){poly[j+1]=add(poly[j+1],cur[j]);poly[j]=add(poly[j],mul(tr(A),cur[j]),-1);}for(size_t j=0;j<prev.size();j++)poly[j]=add(poly[j],mul(tr(B),prev[j]),-1);prev=cur;cur=poly;r.Fpoly.push_back(cur);r.terminal=next;if(zero(next)){r.closed=true;break;}current=next;}return r;}
inline json recdump(const Rec&r){json blocks=json::array(),polys=json::array();for(size_t n=0;n<r.Q.size();n++)blocks.push_back({{"Q",dump(r.Q[n])},{"G",dump(r.G[n])},{"A",dump(r.A[n])},{"B",dump(r.B[n])}});for(auto&p:r.Fpoly)polys.push_back(polydump(p));return {{"H",dump(r.H)},{"blocks",blocks},{"polynomials",polys},{"terminal",dump(r.terminal)},{"closed",r.closed},{"levels",r.Q.size()},{"channels",cols(r.Q[0])},{"dimension",r.Q.size()*cols(r.Q[0])},{"status",r.closed?"CLOSED":"INCOMPLETE_OR_PARTIAL_BLOCK_BREAKDOWN"}};}
inline Rec recread(const json&j){Rec r;r.H=read(j.at("H"));eq(r.H,tr(r.H),"Recurrence Hamiltonian self-adjoint");ck(j.at("blocks").is_array()&&!j["blocks"].empty()&&j["blocks"].size()<=64,"Recurrence has1..64 levels");for(auto&b:j["blocks"]){r.Q.push_back(read(b.at("Q")));r.G.push_back(read(b.at("G"),8,8));r.A.push_back(read(b.at("A"),8,8));r.B.push_back(read(b.at("B"),8,8));}for(auto&p:j.at("polynomials"))r.Fpoly.push_back(polyread(p));r.terminal=read(j.at("terminal"));r.closed=j.at("closed").get<bool>();ck(r.Fpoly.size()==r.Q.size()+1,"Terminal polynomial missing");auto k=cols(r.Q[0]);ck(k>=1&&k<=8,"Recurrence channel admission");for(size_t n=0;n<r.Q.size();n++){ck(r.Q[n].size()==r.H.size()&&cols(r.Q[n])==k,"Recurrence block shape");eq(mul(tr(r.Q[n]),r.Q[n]),r.G[n],"Recurrence Gram reconstruction");inverse(r.G[n]);for(size_t m=0;m<n;m++)eq(mul(tr(r.Q[m]),r.Q[n]),z(k,k),"Recurrence interblock orthogonality");auto rhs=add(n+1<r.Q.size()?r.Q[n+1]:r.terminal,mul(r.Q[n],r.A[n]));if(n)rhs=add(rhs,mul(r.Q[n-1],r.B[n]));eq(mul(r.H,r.Q[n]),rhs,"Recurrence source action");eq(mul(r.G[n],r.A[n]),mul(tr(r.A[n]),r.G[n]),"Recurrence metric symmetry");ck(r.Fpoly[n].size()==n+1,"Polynomial degree convention");}eq(r.Fpoly[0][0],eye(k),"Initial polynomial identity");for(size_t n=0;n<r.Q.size();n++){PM next(n+2,z(k,k));for(size_t t=0;t<r.Fpoly[n].size();t++){next[t+1]=add(next[t+1],r.Fpoly[n][t]);next[t]=add(next[t],mul(tr(r.A[n]),r.Fpoly[n][t]),-1);}if(n)for(size_t t=0;t<r.Fpoly[n-1].size();t++)next[t]=add(next[t],mul(tr(r.B[n]),r.Fpoly[n-1][t]),-1);ck(next==r.Fpoly[n+1],"Matrix polynomial recurrence differs");}ck(!r.closed||zero(r.terminal),"False terminal closure");return r;}
inline json recurrence(const json&p){auto h=hamiltonian(p),seed=read(p.at("seeds"));int limit=p.value("max_levels",64);ck(limit>=1&&limit<=64,"Levels1..64");auto r=recurrence_data(h,seed,limit);return recdump(r);}
inline PM creation_data(const Rec&r){ck(r.closed,"Spectral creation requires a closed admitted recurrence");auto levels=r.Q.size(),k=cols(r.Q[0]);PM C(levels,z(r.H.size(),k));for(size_t n=0;n<levels;n++){auto left=mul(r.Q[n],inverse(r.G[n]));for(size_t t=0;t<r.Fpoly[n].size();t++)C[t]=add(C[t],mul(left,r.Fpoly[n][t]));}auto tail=mul(r.Q.back(),inverse(r.G.back()));for(size_t t=0;t<=levels;t++){auto lhs=t<levels?mul(r.H,C[t]):z(r.H.size(),k);if(t)lhs=add(lhs,C[t-1],-1);eq(lhs,scale(mul(tail,r.Fpoly.back()[t]),F(-1)),"Coefficientwise spectral creation residual");if(t<levels)eq(mul(tr(r.Q[0]),C[t]),t?z(k,k):eye(k),"Source creation seed normalization");}return C;}
inline json creation(const json&p){auto r=recread(p.at("recurrence"));auto c=creation_data(r);json out={{"coefficients",polydump(c)},{"terminal_factor",dump(mul(r.Q.back(),inverse(r.G.back())))},{"degree",c.size()-1},{"dimension",r.Q.size()*cols(r.Q[0])},{"off_shell_identity","(H-x)C=-Q_last G_last^-1 F_terminal"},{"normalization","Q0^T C=I"}};if(p.contains("reference")){auto ref=read(p["reference"]);reference(r.H,ref,scalar(p.at("reference_energy")));out["reference_eigenstate_verified"]=true;out["reference_energy"]=p["reference_energy"];out["transition_coordinate"]="omega=x-reference_energy";}if(p.contains("x"))out["evaluated"]=dump(eval(c,scalar(p["x"])));return out;}

inline json pair_roots(const json&p){auto H=hamiltonian(p),W=read(p.at("frame"));ck(W.size()==H.size()&&cols(W)==4&&rref(W).pivots.size()==4,"Independent four-column native pair frame required");auto par=p.at("parameters");F mu=scalar(par.at("mu")),a=scalar(par.at("a")),b=scalar(par.at("b")),c=scalar(par.at("c")),g=scalar(par.at("g")),offset=scalar(par.at("offset"));F delta=(a-b)/F(2),J=(a+b)/F(2);auto B=z(4,4);B[0][0]=mu+J-F(2)*c;B[3][3]=mu+J+F(2)*c;B[1][1]=B[2][2]=mu-J;B[0][3]=B[3][0]=delta;B[1][2]=B[2][1]=-delta;auto K=add(scale(B,g),scale(eye(4),offset));eq(mul(H,W),mul(W,K),"Full-source native quartet pair contract");auto G=mul(tr(W),W);F norm=G[0][0];ck(!norm.zero(),"Nonzero pair frame norm");eq(G,scale(eye(4),norm),"Pair frame must have a common orthogonal normalization");bool chart=!g.zero()&&!c.zero();return {{"pair_equation_ascending",{dump(-delta),dump(-F(4)*c),dump(delta)}},{"energy_constant",dump(offset+g*(mu+J-F(2)*c))},{"energy_z_coefficient",dump(g*delta)},{"spectral_chart_admitted",chart},{"root_product",chart?json("1"):json(nullptr)},{"root_sum_equation_ascending",{dump(-F(4)*c),dump(F(2)*delta),dump(c)}},{"reciprocal_quartic_ascending",{dump(c),dump(F(2)*delta),dump(-F(2)*c),dump(F(2)*delta),dump(c)}},{"g_zero_all_pair_states_eigen",g.zero()},{"delta_zero_pure_state_limits",delta.zero()},{"source_residual_verified",true},{"root_representation","Exact polynomial relations; no numerical root approximation is returned"}};}

using I=long long;using IM=std::vector<std::vector<I>>;
inline I powmod(I a,I n,I p){I v=1;while(n){if(n&1)v=v*a%p;a=a*a%p;n>>=1;}return v;}
struct Mod {
 I p,root;
 Mod(I prime):p(prime),root(0){ck(p>=3&&p<=10000019&&mpz_probab_prime_p(mpz_class(static_cast<long>(p)).get_mpz_t(),25)>0,"Admitted modular prime3..10000019");if(D){ck(p%4==3,"Quadratic embedding prime must equal3 modulo4");root=powmod(D%p,(p+1)/4,p);ck(root*root%p==D%p,"Quadratic field has no selected embedding at this prime");}}
 I norm(I v)const{v%=p;return v<0?v+p:v;}
 I rat(const mpq_class&q)const{I a=mpz_fdiv_ui(q.get_num().get_mpz_t(),p),b=mpz_fdiv_ui(q.get_den().get_mpz_t(),p);ck(b!=0,"Modular denominator loss");return a*powmod(b,p-2,p)%p;}
 I val(const F&v)const{return (rat(v.a)+root*rat(v.b))%p;}
 IM z(size_t n,size_t k)const{return IM(n,std::vector<I>(k));}
 IM read(const M&a)const{auto b=z(a.size(),cols(a));for(size_t i=0;i<a.size();i++)for(size_t j=0;j<cols(a);j++)b[i][j]=val(a[i][j]);return b;}
 IM add(IM a,const IM&b,int s=1)const{for(size_t i=0;i<a.size();i++)for(size_t j=0;j<a[0].size();j++)a[i][j]=norm(a[i][j]+s*b[i][j]);return a;}
 IM scale(IM a,I f)const{for(auto&r:a)for(auto&v:r)v=v*f%p;return a;}
 IM mul(const IM&a,const IM&b)const{auto c=z(a.size(),b[0].size());for(size_t i=0;i<a.size();i++)for(size_t k=0;k<b.size();k++)if(a[i][k])for(size_t j=0;j<b[0].size();j++)if(b[k][j])c[i][j]=(c[i][j]+a[i][k]*b[k][j])%p;return c;}
 IM eval(const PM&a,const F&x)const{auto v=z(a[0].size(),cols(a[0]));for(auto it=a.rbegin();it!=a.rend();++it)v=add(scale(v,val(x)),read(*it));return v;}
 json certificate(const IM&a)const{IM basis;std::vector<int>pivots,rows;for(size_t i=0;i<a.size();i++){auto v=a[i];for(size_t k=0;k<basis.size();k++){I t=v[pivots[k]];for(size_t j=0;j<v.size();j++)v[j]=norm(v[j]-t*basis[k][j]);}size_t j=0;while(j<v.size()&&!v[j])j++;if(j==v.size())continue;I t=powmod(v[j],p-2,p);for(auto&x:v)x=x*t%p;basis.push_back(v);pivots.push_back(j);rows.push_back(i);}auto n=rows.size();auto minor=z(n,n);for(size_t i=0;i<n;i++)for(size_t j=0;j<n;j++)minor[i][j]=a[rows[i]][pivots[j]];auto b=minor;I det=1;for(size_t j=0;j<n;j++){size_t k=j;while(k<n&&!b[k][j])k++;ck(k<n,"Rank certificate minor singular");if(k!=j){std::swap(b[k],b[j]);det=norm(-det);}I f=b[j][j];det=det*f%p;I inv=powmod(f,p-2,p);for(size_t i=j+1;i<n;i++){I t=b[i][j]*inv%p;for(size_t c=j;c<n;c++)b[i][c]=norm(b[i][c]-t*b[j][c]);}}return {{"rank_lower_bound",n},{"rows",rows},{"columns",pivots},{"minor",minor},{"determinant",det},{"prime",p},{"sqrt_embedding",root}};}
};

struct Lift {Rec rec;std::vector<M>seed;M reference;F energy;std::string action;};
inline Lift liftread(const json&p){Lift l;l.rec=recread(p.at("recurrence"));ck(l.rec.closed,"Operator lift requires a closed source recurrence");for(auto&a:p.at("seed_operators")){auto s=read(a);ck(s.size()==l.rec.H.size()&&cols(s)==s.size(),"Seed operator source shape");l.seed.push_back(s);}ck(l.seed.size()==cols(l.rec.Q[0]),"Seed operator channel count");l.reference=read(p.at("reference"));ck(l.reference.size()==l.rec.H.size()&&cols(l.reference)==1&&!zero(l.reference),"Nonzero lift reference required");auto prepared=z(l.reference.size(),l.seed.size());for(size_t a=0;a<l.seed.size();a++){auto v=mul(l.seed[a],l.reference);for(size_t i=0;i<v.size();i++)prepared[i][a]=v[i][0];}eq(prepared,l.rec.Q[0],"Operator words differ from recurrence seed preparation");l.action=p.at("action").get<std::string>();ck(l.action=="LEFT"||l.action=="COMMUTATOR_REFERENCE","Unknown operator action");if(l.action=="COMMUTATOR_REFERENCE"){l.energy=scalar(p.at("reference_energy"));reference(l.rec.H,l.reference,l.energy);}return l;}
inline std::vector<std::vector<IM>> liftmod(const Lift&l,const Mod&m){auto n=l.rec.Q.size(),k=l.seed.size();std::vector<std::vector<IM>>L(n+1,std::vector<IM>(k));for(size_t a=0;a<k;a++)L[0][a]=m.read(l.seed[a]);auto h=m.read(l.rec.H),ref=m.read(l.reference);for(size_t t=0;t<n;t++){auto A=m.read(l.rec.A[t]),B=m.read(l.rec.B[t]);for(size_t a=0;a<k;a++){L[t+1][a]=m.mul(h,L[t][a]);if(l.action=="COMMUTATOR_REFERENCE")L[t+1][a]=m.add(m.add(L[t+1][a],m.mul(L[t][a],h),-1),m.scale(L[t][a],m.val(l.energy)));for(size_t b=0;b<k;b++){L[t+1][a]=m.add(L[t+1][a],m.scale(L[t][b],A[b][a]),-1);if(t)L[t+1][a]=m.add(L[t+1][a],m.scale(L[t-1][b],B[b][a]),-1);}auto v=m.mul(L[t][a],ref),q=m.read(l.rec.Q[t]);for(size_t i=0;i<v.size();i++)ck(v[i][0]==q[i][a],"Lift reconstruction on reference");}}for(size_t a=0;a<k;a++)ck(m.mul(L[n][a],ref)==m.z(ref.size(),1),"Terminal reference action must vanish");return L;}
inline std::vector<IM> creator_mod(const Lift&l,const Mod&m,const std::vector<std::vector<IM>>&L,const F&x,bool terminal){auto k=l.seed.size(),n=l.rec.Q.size();std::vector<IM>out(k,m.z(l.rec.H.size(),l.rec.H.size()));for(size_t t=0;t<n;t++){auto cf=m.mul(m.read(inverse(l.rec.G[t])),m.eval(l.rec.Fpoly[t],x));for(size_t a=0;a<k;a++)for(size_t b=0;b<k;b++)out[b]=m.add(out[b],m.scale(L[t][a],cf[a][b]));}if(terminal)out.insert(out.end(),L[n].begin(),L[n].end());return out;}

inline json exchange(const json&p){auto mode=p.at("mode").get<std::string>();
 if(mode=="LIFT_RANK"){
  auto l=liftread(p.at("lift"));auto x=scalar(p.at("u")),y=scalar(p.at("v"));bool terminals=p.value("include_terminal",false),onref=p.value("on_reference",false);auto primes=p.at("primes").get<std::vector<long>>();ck(!primes.empty()&&primes.size()<=4,"One to four modular embeddings");json results=json::array();bool certified=false;for(long prime:primes){Mod m(prime);auto L=liftmod(l,m);auto U=creator_mod(l,m,L,x,terminals),V=creator_mod(l,m,L,y,terminals);size_t k=U.size(),n=l.rec.H.size();ck(k<=8,"At most8 exchange channels");auto rev=m.z(onref?n:n*n,k*k),both=m.z(onref?n:n*n,2*k*k);auto ref=m.read(l.reference);for(size_t a=0;a<k;a++)for(size_t b=0;b<k;b++){auto f=m.mul(U[a],V[b]),r=m.mul(V[a],U[b]);if(onref){f=m.mul(f,ref);r=m.mul(r,ref);}size_t width=onref?1:n;for(size_t i=0;i<n;i++)for(size_t j=0;j<width;j++){rev[i*width+j][a*k+b]=r[i][j];both[i*width+j][a*k+b]=r[i][j];both[i*width+j][k*k+a*k+b]=f[i][j];}}auto cr=m.certificate(rev),ca=m.certificate(both);size_t upper=k*k;if(onref&&terminals)upper=k*l.seed.size();bool no=ca["rank_lower_bound"].get<size_t>()>upper;certified|=no;results.push_back({{"reverse",cr},{"combined",ca},{"reverse_rank_upper_bound",upper},{"nonclosure_certified",no}});}return {{"status",certified?"NONCLOSURE_CERTIFIED":"MODULAR_TEST_INCONCLUSIVE"},{"certificates",results},{"u",dump(x)},{"v",dump(y)},{"include_terminal",terminals},{"on_reference",onref},{"scope","Nonzero minor certifies generic polynomial operator-family nonclosure for this lift; lower ranks alone do not certify closure"}};
 }
 if(mode=="CONSTANT_EXCHANGE"){
  std::vector<PM>family;for(auto&a:p.at("family"))family.push_back(polyread(a));size_t k=family.size();ck(k>=1&&k<=4,"Constant exchange admits1..4 channels");auto R=read(p.at("R"),16,16);ck(R.size()==k*k&&cols(R)==k*k,"Channel exchange matrix shape");size_t degree=family[0].size(),n=family[0][0].size();for(auto&f:family){ck(f.size()==degree,"Common polynomial degree required");for(auto&a:f)ck(a.size()==n&&cols(a)==n,"Square common source operators required");}bool closes=true;json failures=json::array();for(size_t a=0;a<k;a++)for(size_t b=0;b<k;b++)for(size_t i=0;i<degree;i++)for(size_t j=0;j<degree;j++){auto residual=mul(family[a][i],family[b][j]);for(size_t c=0;c<k;c++)for(size_t d=0;d<k;d++)residual=add(residual,scale(mul(family[c][j],family[d][i]),R[a*k+b][c*k+d]),-1);if(!zero(residual)){closes=false;if(failures.size()<8)failures.push_back({{"channels",{a,b}},{"degrees",{i,j}},{"residual",dump(residual)}});}}auto R12=kron(R,eye(k)),R23=kron(eye(k),R);auto braid=add(mul(mul(R12,R23),R12),mul(mul(R23,R12),R23),-1);auto reversal=add(mul(R,R),eye(k*k),-1);return {{"coefficientwise_exchange",closes},{"three_exchange_consistency",zero(braid)},{"reversal_consistency",zero(reversal)},{"exchange_failures",failures},{"braid_residual",dump(braid)},{"reversal_residual",dump(reversal)},{"scope","Exact constant exchange coefficients for the supplied polynomial family, including three-channel-factor braid consistency"}};
 }
 throw std::invalid_argument("Unknown exchange mode");
}

inline json terminal(const json&p){auto l=liftread(p.at("lift"));auto mode=p.at("mode").get<std::string>();ck(mode=="MODULAR_ACTION"||mode=="EXACT_ACTION","Unknown terminal action mode");auto frame=read(p.at("frame"));ck(frame.size()==l.rec.H.size()&&rref(frame).pivots.size()==cols(frame),"Independent compatible terminal frame required");auto left=mul(inverse(mul(tr(frame),frame)),tr(frame)),K=mul(left,mul(l.rec.H,frame));eq(mul(l.rec.H,frame),mul(frame,K),"Terminal frame must be invariant");json out; if(mode=="MODULAR_ACTION"){json certs=json::array();for(auto&pr:p.at("primes")){Mod m(pr.get<long>());auto L=liftmod(l,m);IM total;auto fm=m.read(frame);for(auto&a:L.back()){auto action=m.mul(a,fm);total.insert(total.end(),action.begin(),action.end());}certs.push_back(m.certificate(total));}out={{"certificates",certs},{"rank_upper_bound",cols(frame)},{"reference_terminal_zero",true},{"exact_rank_assigned",false}};}else{
  std::vector<M>cur,prev(l.seed.size(),z(frame.size(),cols(frame)));for(auto&s:l.seed)cur.push_back(mul(s,frame));auto initial=stack(cur);for(size_t t=0;t<l.rec.Q.size();t++){std::vector<M>next(cur.size());for(size_t a=0;a<cur.size();a++){next[a]=mul(l.rec.H,cur[a]);if(l.action=="COMMUTATOR_REFERENCE")next[a]=add(add(next[a],mul(cur[a],K),-1),scale(cur[a],l.energy));for(size_t b=0;b<cur.size();b++){next[a]=add(next[a],scale(cur[b],l.rec.A[t][b][a]),-1);if(t)next[a]=add(next[a],scale(prev[b],l.rec.B[t][b][a]),-1);}}prev=cur;cur=next;}auto T=stack(cur);auto reduction=rref(T);auto N=nullspace(reduction);auto transported=mul(T,mul(K,N));out={{"terminal_action",dump(T)},{"rank",reduction.pivots.size()},{"kernel",dump(N)},{"kernel_source",dump(mul(frame,N))},{"kernel_after_H",dump(transported)},{"kernel_after_H_rank",rref(transported).pivots.size()},{"seed_rank",rref(initial).pivots.size()},{"reference_terminal_zero",true}};
 }out["operator_identity"]=l.action=="LEFT"?"(H-x)B=L_terminal G_last^-1 F_last-L_last G_last^-1 F_terminal":"[H,B]-(x-Eref)B=L_terminal G_last^-1 F_last-L_last G_last^-1 F_terminal";return out;}

inline json execute(const std::string&op,const json&p){field(p);json r;if(op=="SOURCE_OPERATOR_WORD")r=words(p);else if(op=="SOURCE_SUBSPACE")r=subspace(p);else if(op=="NATIVE_PAIR_ROOTS")r=pair_roots(p);else if(op=="BLOCK_SOURCE_RECURRENCE")r=recurrence(p);else if(op=="SOURCE_SPECTRAL_CREATION")r=creation(p);else if(op=="SOURCE_WORD_EXCHANGE")r=exchange(p);else if(op=="SOURCE_TERMINAL_ACTION")r=terminal(p);else throw std::invalid_argument("Unknown source algebra operation");r["field"]={{"radicand",D}};r["native_assertions"]=assertions;r["arithmetic"]="EXACT_Q_OR_REAL_QUADRATIC_GMP";return r;}
}
