#include "discrepancy.cpp"
Q input_energy(long s){long u=root(2*s-1);Q E=0;for(long n=1;n<=u;n*=2)E+=full(source(n,std::min(n,u-n+1)));need(E>=1,"Actual smaller-source normalization");return E;}
J feature(long s,long t){auto mu=mobius(2*s);long M=0,N=0,area=0;for(long i=0;i<t;++i){if(i)area+=M;M+=mu[s+i];N+=mu[s+i]*mu[s+i];}return J::array({str(rat(M,s)),str(rat(area,s*s)),str(rat(N,s)),str(rat(t,s))});}
J dual(J row,bool deep){long s=row.at("s"),t=row.at("t"),m=row.at("m");auto b=basis(s,m);Q E=input_energy(s),F=0,norm=0,pairing=0;J coeff=J::array(),gram=J::array();for(long k=0;k<=m;++k){Q A=parse(row["moments"][k]),g=b.d[k];if(k)g*=k*(k+1);Q c=A/g;need(g*c==A,"Exact Gram solve");F+=A*A/g;norm+=g*c*c;pairing+=A*c;gram.push_back(str(g));coeff.push_back(str(c));}need(F==parse(row["low_energy"])&&norm==F&&pairing==F,"Dual norm and attainment");
 J slacks=J::array();for(auto c:std::vector<std::string>{"1/16","1/8","1/4","1/2","1","2"}){Q B(c);B.canonicalize();slacks.push_back({{"id","SD-C"+c+"-P0"},{"bound",c},{"slack",str(B*E-F)},{"passes",B*E>=F}});}
 J result={{"schema","RH_SIGNED_DIVISOR_WITNESS_R1"},{"s",s},{"t",t},{"u",root(2*s-1)},{"m",m},{"input_energy",str(E)},{"dual_envelope",str(F)},{"normalized_demand",str(F/E)},{"gram_diagonal",gram},{"maximizer",coeff},{"zero_functional",F==0},{"attainment",{{"functional",str(pairing)},{"derivative_norm",str(norm)}}},{"features",feature(s,t)},{"candidate_slacks",slacks},{"original",row},{"U",nullptr},{"tau",nullptr},{"baseline",nullptr},{"original_endpoint_metadata","block contribution; no unique roster endpoint selected"},{"certificate","d J(c)-(ell.c)^2 = sum_i<j G_i G_j (c_i cstar_j-c_j cstar_i)^2"}};
 if(deep){result["complete_divisor_modes"]=divisor(b,t,m);result["signed_decomposition"]=discrepancy(s,t);need(parse(result["signed_decomposition"]["low_energy"])==F,"Complete-source drift/discrepancy equality");}return result;
}
Q mean_target(const std::vector<J>&rows){Q q=0;for(auto r:rows)q+=parse(r["normalized_demand"]);return q/rows.size();}
Q error(const std::vector<J>&rows,Q mean){Q e=0;for(auto r:rows)e+=sq(parse(r["normalized_demand"])-mean);return e;}
Q predict(const J&model,const J&f){if(model["feature"].is_null())return parse(model["mean"]);long k=model["feature"];return parse(f[k])<=parse(model["threshold"])?parse(model["left_mean"]):parse(model["right_mean"]);}
J learn(const J&input){std::vector<J> rows;J reserved=J::array();std::set<std::string> keys;for(auto r:input){std::string key=std::to_string(r["s"].get<long>())+":"+std::to_string(r["t"].get<long>());need(keys.insert(key).second,"Duplicate learning window");Q E=parse(r["input_energy"]),F=parse(r["dual_envelope"]);need(E>=1&&F/E==parse(r["normalized_demand"]),"Learning target integrity");if(r["s"]==4096)reserved.push_back(r);else rows.push_back(r);}need(!rows.empty(),"Training corpus empty");Q avg=mean_target(rows),best=error(rows,avg);J model={{"feature",nullptr},{"mean",str(avg)},{"squared_error",str(best)},{"fit","NATIVE_GMP_EXACT_REGRESSION_STUMP"},{"target","joint_dual_envelope/actual_smaller_source_energy"},{"features",{"M/s","prefix_area/s^2","N/s","t/s"}},{"training_rows",rows.size()},{"held_out_scale",4096},{"reserved_rows",reserved.size()}};
 for(long k=0;k<4;++k){std::set<Q> values;for(auto r:rows)values.insert(parse(r["features"][k]));for(Q split:values){std::vector<J> left,right;for(auto r:rows)(parse(r["features"][k])<=split?left:right).push_back(r);if(left.empty()||right.empty())continue;Q l=mean_target(left),r=mean_target(right),e=error(left,l)+error(right,r);if(e<best){best=e;model["feature"]=k;model["threshold"]=str(split);model["left_mean"]=str(l);model["right_mean"]=str(r);model["squared_error"]=str(e);}}}
 J jobs=J::array();long s=1024;std::vector<std::pair<Q,long>> scores;for(long t=1;t<=s;++t)if(!keys.count(std::to_string(s)+":"+std::to_string(t)))scores.push_back({predict(model,feature(s,t)),t});long anchor_stop=512;Q anchor_gain=-1;for(auto r:rows)if(r["s"]==s && parse(r["normalized_demand"])>anchor_gain){anchor_gain=parse(r["normalized_demand"]);anchor_stop=r["t"].get<long>();}std::stable_sort(scores.begin(),scores.end(),[anchor_stop](auto a,auto b){if(a.first!=b.first)return a.first>b.first;auto da=std::abs(a.second-anchor_stop),db=std::abs(b.second-anchor_stop);return da==db?a.second<b.second:da<db;});for(auto [score,t]:scores){if(jobs.size()>=8)break;jobs.push_back({{"s",s},{"t",t},{"predicted_demand",str(score)},{"selection_role","LEARNED"},{"reason","Native regression joint-demand prediction; tied scores prefer neighborhoods of the measured same-scale demand maximum"}});}for(long t:std::vector<long>{256,512,768,1024})if(!keys.count("1024:"+std::to_string(t))){bool exists=false;for(auto j:jobs)if(j["t"]==t)exists=true;if(!exists)jobs.push_back({{"s",1024},{"t",t},{"selection_role","FRESH"},{"reason","Deterministic next-scale prefix coverage"}});}
 return {{"status","TRAINED"},{"model",model},{"jobs",jobs},{"retained_rows",input.size()},{"training_rows",rows.size()},{"reserved_rows",reserved.size()},{"allocation",{{"learned_limit",40},{"fresh_limit",24}}}};
}
J screen(long s){need(s==1024||s==2048||s==4096||s==8192,"Declared coverage ladder");long m=std::min(s-1,long(root(s)+(root(s)*root(s)<s)));auto b=basis(s,m);auto mu=mobius(2*s);std::vector<Z>A(m+1);Q E=input_energy(s),peak=-1;J ties=J::array(),rows=J::array();for(long t=0;t<=s;++t){if(t)for(long k=0;k<=m;++k)A[k]+=mu[s+t-1]*b.p[k][t-1];Q F=0;for(long k=0;k<=m;++k){Q d=b.d[k];if(k)d*=k*(k+1);F+=Q(A[k]*A[k])/d;}Q demand=F/E;rows.push_back(str(demand));if(demand>peak){peak=demand;ties=J::array({t});}else if(demand==peak)ties.push_back(t);}
 J failures=J::array();for(std::string c:{"1/16","1/8","1/4","1/2","1","2"}){Q B(c);B.canonicalize();long count=0;for(auto r:rows)if(parse(r)>B)++count;failures.push_back({{"candidate","SD-C"+c+"-P0"},{"failures",count}});}J witnesses=J::array();for(auto t:ties)witnesses.push_back(dual(anchor(s,t),true));return {{"s",s},{"prefixes",s+1},{"scope","COMPLETE_PREFIX_JOINT_DUAL_GAIN; original full/projected energy reconstructed at all maximum ties"},{"max_demand",str(peak)},{"all_maximum_ties",ties},{"candidate_failures",failures},{"compact_prefix_demands",rows},{"witnesses",witnesses},{"input_energy",str(E)}};
}
int retained_signed_divisor_main(){try{J input;std::cin>>input;auto req=input.at(0);auto p=req.at("payload");auto contract=reference(p.at("contract"));need(contract["id"]=="RH-SIGNED-DIVISOR-R1","Contract binding");std::string op=req.at("op");J r;if(op=="RH_SIGNED_DIVISOR_ADMIT_R1"){auto x=reference(p.at("source"));r=dual(x,false);}else if(op=="RH_SIGNED_DIVISOR_WITNESS_R1"){if(p.contains("original_source")){auto source=reference(p["original_source"]);need(source["s"]==p["s"]&&source["t"]==p["t"],"Original owning-engine source endpoint");}r=dual(anchor(p.at("s"),p.at("t")),true);if(p.contains("original_source"))r["owning_source"]=p["original_source"];}else if(op=="GEN3_TRANSFER_RH_SIGNED_DIVISOR_R1"){J rows=J::array();for(auto ref:p.at("witnesses"))rows.push_back(reference(ref));r=learn(rows);}else if(op=="RH_SIGNED_DIVISOR_SCREEN_R1")r=screen(p.at("s"));else throw std::runtime_error("Unknown signed-divisor operation");r["contract_sha256"]=p["contract"]["sha256"];std::cout<<J({{"ok",true},{"result",r}}).dump()<<std::endl;}catch(const std::exception&e){std::cout<<J({{"ok",false},{"error",e.what()}}).dump()<<std::endl;return 1;}}
