#include "campaign.cpp"
std::vector<Q> flux(const std::vector<int>&a){long s=a.size(),M=0,P=0;for(int v:a)M+=v;std::vector<Q>q(s+1);for(long r=1;r<=s;++r){P+=a[r-1];q[r]=Q(P)-rat(r*M,s);}return q;}
Q inner(const std::vector<int>&a,const std::vector<int>&b){long s=a.size(),M=0,B=0;for(int v:a)M+=v;for(int v:b)B+=v;auto q=flux(a),c=flux(b);Q z=rat(M*B,s);for(long r=1;r<s;++r)z+=q[r]*c[r]/(r*(s-r));return z;}
std::string sourcehash(const std::vector<int>&a){std::string text;for(int v:a)text+=std::to_string(v)+",";return digest(text);}
J forcing(long s,long t){
 need(s>=1&&s<=8192&&(s&(s-1))==0&&t>=0&&t<=s,"Bounded original dyadic source");
 auto mu=mobius(4*s);auto a=source(s,t),z=source(2*s,2*t);std::vector<int>b(s),v(s),d(s),e(s),o(s);long M=0,B=0,N=0,Nfine=0;long checks=0;
 for(long i=0;i<s;++i){long n=s+i;e[i]=i<t&&n%2==0?mu[n]:0;o[i]=i<t?mu[2*n+1]:0;b[i]=e[i]+o[i];v[i]=z[2*i]+z[2*i+1];d[i]=z[2*i]-z[2*i+1];need(v[i]==-a[i]+b[i],"Exact parity/odd-source pair");++checks;M+=a[i];B+=b[i];N+=a[i]*a[i];Nfine+=z[2*i]*z[2*i]+z[2*i+1]*z[2*i+1];}
 auto c=flux(v),q=flux(z),qa=flux(a),qb=flux(b);Q Qa=full(a),Qb=full(b),ab=inner(a,b),Qv=full(v),Qz=full(z),S=0,I=0,eps=0,Omega=0,sos=0;std::vector<Q>w(s);std::vector<long>h(s+1);for(long r=0;r<=s;++r)h[r]=r*(s-r);
 for(long r=0;r<=s;++r){need(q[2*r]==c[r]&&c[r]==-qa[r]+qb[r],"Even cut with both endpoints");++checks;if(r&&r<s)S+=c[r]*c[r]/h[r];}
 for(long i=0;i<s;++i){w[i]=rat(1,(2*i+1)*(2*s-2*i-1));Q u=c[i]+c[i+1];need(q[2*i+1]==(u+d[i])/2,"Complete odd cut");++checks;S-=w[i]*u*u;I+=w[i]*u*d[i]/2;eps+=w[i]*d[i]*d[i]/4;Omega+=w[i];Q gi=h[i]?Q(c[i]/h[i]):Q(0),gj=h[i+1]?Q(c[i+1]/h[i+1]):Q(0);sos+=w[i]*h[i]*h[i+1]*(gi-gj)*(gi-gj)/4;}
 S/=4;for(long r=1;r<s;++r)sos+=(w[r-1]+w[r])*c[r]*c[r]/h[r]/8;
 Q A=Qb/2-ab,R=-S+I+eps,excess=A-Qa/2;need(S==sos&&S>=0,"Supplied interpolation-loss SOS");need(Qv==Qa+Qb-2*ab,"Polarized full energy");need(Qz==Qv/2+R&&Qz==Qa/2+A+R,"Full forced energy with mean");need(eps>=0&&eps<=Omega&&Omega<=1&&I<=2*(1-Omega/s)&&-I<=2*(1-Omega/s)&&R<=3,"Supplied one-sided remainder");checks+=4;
 Q QaMean=rat(M*M,s),QbMean=rat(B*B,s),abMean=rat(M*B,s);J odd=nullptr;if(t<s){auto zz=z;zz[2*t]=mu[2*s+2*t];Q qq=full(zz),increment=qq-Qz;need(increment<=2&&qq<=Qa/2+A+5,"Odd-stop full original upper bound");++checks;odd={{"t",2*t+1},{"Q",str(qq)},{"increment",str(increment)},{"upper_margin",str(Qa/2+A+5-qq)}};}
 Q Qe=full(e),Qo=full(o),eo=inner(e,o),ae=inner(a,e),ao=inner(a,o);need(A==Qe/2+Qo/2+eo-ae-ao,"Explicit signed parity causes");++checks;
 J candidate=J::array();for(std::string v0:{"0","1/16","1/8","1/4","1/2","1","2"}){Q C(v0);C.canonicalize();candidate.push_back({{"C",v0},{"p",0},{"slack",str(C-excess)},{"passes",excess<=C}});}
 return {{"schema","RH_DYADIC_COUPLED_FORCING_WITNESS_R1"},{"s",s},{"t",t},{"fine_s",2*s},{"fine_t",2*t},{"N",N},{"fine_N",Nfine},{"M",M},{"B",B},{"U",nullptr},{"tau",nullptr},{"baseline",nullptr},{"endpoint_provenance","Original stopped blocks; no unique roster normalization assigned"},{"a_sha256",sourcehash(a)},{"b_sha256",sourcehash(b)},{"fine_source_sha256",sourcehash(z)},{"Q_a",str(Qa)},{"Q_b",str(Qb)},{"inner_ab",str(ab)},{"Q_v",str(Qv)},{"A",str(A)},{"S",str(S)},{"S_sos",str(sos)},{"I",str(I)},{"epsilon",str(eps)},{"Omega",str(Omega)},{"R",str(R)},{"Q_fine",str(Qz)},{"excess",str(excess)},{"mean_forcing",str(QbMean/2-abMean)},{"cut_forcing",str((Qb-QbMean)/2-(ab-abMean))},{"mean_inner_ab",str(abMean)},{"cut_inner_ab",str(ab-abMean)},{"Q_a_mean",str(QaMean)},{"parity_causes",{{"Q_even",str(Qe)},{"Q_odd",str(Qo)},{"even_odd_inner",str(eo)},{"a_even_inner",str(ae)},{"a_odd_inner",str(ao)}}},{"projected",project(s,t)},{"odd_stop",odd},{"features",J::array({str(rat(M,s)),str(rat(B,s)),str(rat(N,s)),str(rat(t,s))})},{"candidate_slacks",candidate},{"checks",checks}};
}
// Common-denominator kernel columns give exact O(s) prefix energy updates.
struct FastKernel {long s;Z L=1,den;std::vector<Z>H;FastKernel(long n):s(n){for(long j=1;j<s;++j)mpz_lcm_ui(L.get_mpz_t(),L.get_mpz_t(),j);H.resize(s);for(long j=1;j<s;++j)H[j]=H[j-1]+L/j;den=L*s*s;}
 Z head(long j){return Z(L+s*(2*H[s-1]-H[j]));}Z diagonal(long j){return Z(head(j)-s*H[s-j-1]);}};
struct EnergyRun {FastKernel&k;long M=0;Z weighted=0,numerator=0;EnergyRun(FastKernel&x):k(x){}void add(long j,long a){numerator+=2*a*(k.head(j)*M-k.s*weighted)+a*a*k.diagonal(j);M+=a;weighted+=a*k.H[k.s-j-1];}Q value(){return Q(numerator)/k.den;}};
struct ProjectionRun{long s,M=0,N=0;std::vector<Cell>cells;std::vector<Q>z,d;ProjectionRun(long n):s(n),cells(geometry(n)),z(cells.size()),d(cells.size()){}J add(long t,int a){if(t){long i=t-1;M+=a;N+=a*a;for(size_t j=0;j<cells.size();++j){auto&c=cells[j];Q beta=i<c.l?Q(c.W-c.offset):i>=c.h?Q(-c.offset):c.beta[i-c.l];z[j]+=a*beta;d[j]+=a*a*beta*beta;}}Q E=rat(M*M,s),D=rat(N,s);for(size_t j=0;j<cells.size();++j){E+=z[j]*z[j]/cells[j].W;D+=d[j]/cells[j].W;}Q x=E-D;return {{"Qhat",str(E)},{"D_adm",str(D)},{"X_adm",str(x)},{"positive_X",str(std::max(Q(0),x))}};}};
J scan_forcing(long s){need(s==32||s==512||s==4096||s==8192,"Declared bounded scan scales");auto mu=mobius(4*s);FastKernel k(s),fine(2*s);EnergyRun ar(k),br(k),vr(k),zr(fine);ProjectionRun pr(s);Q maxQ=-1,maxX=-1,maxEx=-100,minA=100;J tq=J::array(),tx=J::array(),te=J::array(),ta=J::array(),fails=J::array();std::vector<long>bad(7);std::vector<std::string>Cs={"0","1/16","1/8","1/4","1/2","1","2"};long negative=0;J compact=J::array();
 auto up=[](Q value,long t,Q&peak,J&ties){if(value>peak){peak=value;ties=J::array({t});}else if(value==peak)ties.push_back(t);};
 for(long t=0;t<=s;++t){long a=0;if(t){long i=t-1,n=s+i;a=mu[n];long b=(n%2==0?mu[n]:0)+mu[2*n+1];ar.add(i,a);br.add(i,b);vr.add(i,-a+b);zr.add(2*i,mu[2*n]);zr.add(2*i+1,mu[2*n+1]);}Q Qa=ar.value(),Qb=br.value(),Qv=vr.value(),ab=(Qa+Qb-Qv)/2,A=Qb/2-ab,ex=A-Qa/2;auto p=pr.add(t,a);Q X=parse(p["positive_X"]);up(Qa,t,maxQ,tq);up(X,t,maxX,tx);up(ex,t,maxEx,te);if(A<minA){minA=A;ta=J::array({t});}else if(A==minA)ta.push_back(t);if(A<0)++negative;for(size_t j=0;j<Cs.size();++j)if(ex>Q(Cs[j]))++bad[j];compact.push_back({{"t",t},{"Q_a",str(Qa)},{"A",str(A)},{"excess",str(ex)},{"positive_X",str(X)}});}
 for(size_t j=0;j<Cs.size();++j)fails.push_back({{"C",Cs[j]},{"p",0},{"failures",bad[j]}});
 std::set<long>stops;for(auto ties:{tq,tx,te,ta})for(auto t:ties)stops.insert(t.get<long>());J witnesses=J::array();for(long t:stops){auto w=forcing(s,t);auto row=compact[t];need(w["Q_a"]==row["Q_a"]&&w["A"]==row["A"]&&w["excess"]==row["excess"]&&w["projected"]["positive_X"]==row["positive_X"],"Independent direct versus incremental prefix readout at every selected tie");witnesses.push_back(w);}
 return {{"schema","RH_DYADIC_COUPLED_FORCING_SCAN_R1"},{"s",s},{"prefixes",s+1},{"max_Q",str(maxQ)},{"max_Q_ties",tq},{"max_positive_X",str(maxX)},{"max_positive_X_ties",tx},{"max_excess",str(maxEx)},{"max_excess_ties",te},{"min_A",str(minA)},{"min_A_ties",ta},{"negative_A_prefixes",negative},{"candidate_failures",fails},{"compact_prefixes",compact},{"witnesses",witnesses}};
}
J forcelearn(const J&refs){std::vector<J>rows;J held=J::array();std::set<std::string>keys;for(auto ref:refs){auto r=reference(ref);need(r["schema"]=="RH_DYADIC_COUPLED_FORCING_WITNESS_R1","Typed forcing witness");need(parse(r["A"])==parse(r["Q_b"])/2-parse(r["inner_ab"]),"Complete signed training target");std::string key=std::to_string(r["s"].get<long>())+":"+std::to_string(r["t"].get<long>());need(keys.insert(key).second,"Distinct source endpoints");if(r["s"]==4096)held.push_back(r);else rows.push_back(r);}
 need(!rows.empty(),"Actual-source forcing training rows");auto mean=[](const std::vector<J>&v){Q sum=0;for(auto r:v)sum+=parse(r["excess"]);return Q(sum/v.size());};auto err=[](const std::vector<J>&v,Q m){Q sum=0;for(auto r:v)sum+=sq(parse(r["excess"])-m);return sum;};Q avg=mean(rows),best=err(rows,avg);J model={{"feature",nullptr},{"mean",str(avg)},{"features",{"M/s","B/s","N/s","t/s"}},{"target","A-Q_a/2"},{"held_out_scale",4096}};
 for(long j=0;j<4;++j){std::set<Q>values;for(auto r:rows)values.insert(parse(r["features"][j]));for(Q v:values){std::vector<J>l,h;for(auto r:rows)(parse(r["features"][j])<=v?l:h).push_back(r);if(l.empty()||h.empty())continue;Q lm=mean(l),hm=mean(h),e=err(l,lm)+err(h,hm);if(e<best){best=e;model["feature"]=j;model["threshold"]=str(v);model["left_mean"]=str(lm);model["right_mean"]=str(hm);}}}
 model["squared_error"]=str(best);J jobs=J::array();long s=512,M=0,B=0,N=0,anchor=0;Q peak=-100;for(auto r:rows)if(r["s"]==s&&parse(r["excess"])>peak){peak=parse(r["excess"]);anchor=r["t"];}auto mu=mobius(4*s);std::vector<std::pair<Q,long>>scores;for(long t=1;t<=s;++t){long n=s+t-1,a=mu[n];M+=a;B+=(n%2==0?mu[n]:0)+mu[2*n+1];N+=a*a;if(keys.count(std::to_string(s)+":"+std::to_string(t)))continue;J f=J::array({str(rat(M,s)),str(rat(B,s)),str(rat(N,s)),str(rat(t,s))});scores.push_back({predict(model,f),t});}std::stable_sort(scores.begin(),scores.end(),[anchor](auto a,auto b){if(a.first!=b.first)return a.first>b.first;return std::abs(a.second-anchor)<std::abs(b.second-anchor);});for(auto [score,t]:scores){if(jobs.size()>=4)break;jobs.push_back({{"s",s},{"t",t},{"predicted_excess",str(score)},{"selection_role","LEARNED"},{"reason","Native exact regression of complete signed forcing excess; tied predictions near observed same-scale maximum"}});}for(long t:{128,384})if(!keys.count("512:"+std::to_string(t))){bool exists=false;for(auto x:jobs)if(x["t"]==t)exists=true;if(!exists)jobs.push_back({{"s",512},{"t",t},{"selection_role","FRESH"},{"reason","Fixed parity-forcing source coverage"}});}
 return {{"schema","RH_DYADIC_FORCING_MODEL_R1"},{"training_rows",rows.size()},{"reserved_rows",held.size()},{"model",model},{"jobs",jobs}};
}
int retained_forcing_main(){try{J input;std::cin>>input;auto req=input.at(0),p=req.at("payload");auto contract=reference(p.at("contract"));need(contract["id"]=="RH-DYADIC-COUPLED-FORCING-R1","Source handoff contract");std::string op=req.at("op");J r;if(op=="RH_DYADIC_COUPLED_FORCING_R1")r=forcing(p.at("s"),p.at("t"));else if(op=="RH_DYADIC_COUPLED_FORCING_SCAN_R1")r=scan_forcing(p.at("s"));else if(op=="GEN3_TRANSFER_RH_DYADIC_FORCING_R1")r=forcelearn(p.at("witnesses"));else throw std::runtime_error("Unknown typed forcing operation");r["contract_sha256"]=p["contract"]["sha256"];std::cout<<J({{"ok",true},{"result",r}}).dump()<<std::endl;}catch(const std::exception&e){std::cout<<J({{"ok",false},{"error",e.what()}}).dump()<<std::endl;return 1;}}
