#include "forcing.cpp"
int signz(const Z&x){return mpz_sgn(x.get_mpz_t());}
struct State{long Ma=0,Mb=0,Mv=0;Z Wa=0,Wb=0,Wv=0,Qa=0,Qb=0,Qv=0;};
struct Paths{long s;FastKernel k;std::vector<State>st;std::vector<Z>E;std::vector<int>alpha,beta,gamma;std::vector<std::string>sig;Paths(long n):s(n),k(n),st(n+1),E(n+1),alpha(n+1),beta(n+1),gamma(n+1),sig(n+1){auto mu=mobius(4*s);for(long t=1;t<=s;++t){long j=t-1,a=mu[s+j],g=mu[2*(s+j)+1],b=((s+j)%2==0?a:0)+g,v=b-a;auto z=st[t-1];Z head=k.head(j),diag=k.diagonal(j),pa=head*z.Ma-s*z.Wa,pb=head*z.Mb-s*z.Wb,pv=head*z.Mv-s*z.Wv;z.Qa+=2*a*pa+a*a*diag;z.Qb+=2*b*pb+b*b*diag;z.Qv+=2*v*pv+v*v*diag;z.Ma+=a;z.Mb+=b;z.Mv+=v;z.Wa+=a*k.H[s-j-1];z.Wb+=b*k.H[s-j-1];z.Wv+=v*k.H[s-j-1];st[t]=z;E[t]=z.Qv-2*z.Qa;alpha[t]=a;beta[t]=b;gamma[t]=g;if(t<s){Z p=k.head(t)*z.Ma-s*z.Wa,q=k.head(t)*z.Mb-s*z.Wb;sig[t]=J::array({a,b,signz(p),signz(q),signz(Z(E[t]-E[t-1])),(s+j)%2}).dump();}}}
 Q value(const Z&z){return Q(z)/(2*k.den);}
 J future(long t,long h){need(t+h<=s,"Complete forecast horizon");Z peak=0;long first=0;for(long j=1;j<=h;++j)if(E[t+j]-E[t]>peak){peak=E[t+j]-E[t];first=j;}return {{"overshoot",str(value(peak))},{"drift",str(value(Z(E[t+h]-E[t])))},{"peak_offset",first}};}
};
std::vector<long> choices(long n){for(long d=2;d*d<=n;++d)if(n%(d*d)==0)return {0};return {-1,1};}
J certificate(Paths&x,long t,long requested){long h=std::min(requested,x.s-t),nodes=0,leaves=0;Z upper=0,lo=0,hi=0;bool first=true;Z start=x.E[t];
 // Inputs are the CURRENT prefix state, index and squarefree support only.
 // No suffix sign table or realized future outcome enters this recursion.
 auto visit=[&](auto&&self,State z,long j,long end)->void{Z change=z.Qv-2*z.Qa-start;if(change>upper)upper=change;if(j==end){++leaves;if(first){lo=hi=change;first=false;}else{if(change<lo)lo=change;if(change>hi)hi=change;}return;}long n=x.s+j;Z head=x.k.head(j),diag=x.k.diagonal(j),pa=head*z.Ma-x.s*z.Wa,pv=head*z.Mv-x.s*z.Wv;for(long a:choices(n))for(long g:choices(2*n+1)){++nodes;long b=(n%2==0?a:0)+g,v=b-a;auto next=z;next.Qa+=2*a*pa+a*a*diag;next.Qv+=2*v*pv+v*v*diag;next.Ma+=a;next.Mv+=v;next.Wa+=a*x.k.H[x.s-j-1];next.Wv+=v*x.k.H[x.s-j-1];self(self,next,j+1,end);}};
 visit(visit,x.st[t],t,t+h);
 return {{"horizon",h},{"requested_horizon",requested},{"support_branches",leaves},{"nodes",nodes},{"overshoot_bound",str(x.value(upper))},{"drift_lower",str(x.value(lo))},{"drift_upper",str(x.value(hi))},{"E_upper",str(x.value(Z(start+upper)))},{"preserves_C1",x.value(Z(start+upper))<=1},{"preserves_half",x.value(Z(start+upper))<=rat(1,2)},{"uses_future_signs",false},{"future_sign_dependencies_relaxed",true}};
}
J calibrate(){Paths x(512);J groups=J::object(),global=J::object();for(long t=1;t<=192;++t){auto key=x.sig[t];if(!groups.contains(key))groups[key]={{"count",0},{"horizons",J::object()}};groups[key]["count"]=groups[key]["count"].get<long>()+1;for(long h:{8,32,64}){auto y=x.future(t,h);std::string hs=std::to_string(h);auto update=[&](J&z){if(z.is_null()){z={{"overshoot_bound",y["overshoot"]},{"drift_lower",y["drift"]},{"drift_upper",y["drift"]}};return;}if(parse(y["overshoot"])>parse(z["overshoot_bound"]))z["overshoot_bound"]=y["overshoot"];if(parse(y["drift"])<parse(z["drift_lower"]))z["drift_lower"]=y["drift"];if(parse(y["drift"])>parse(z["drift_upper"]))z["drift_upper"]=y["drift"];};update(groups[key]["horizons"][hs]);update(global[hs]);}}
 return {{"schema","RH_FROZEN_SOURCE_STATE_FORECAST_R1"},{"calibration_scale",512},{"state_stops",{1,192}},{"last_label_stop",256},{"groups",groups},{"unconditional_calibration",global},{"held_out_used_for_fitting",false}};
}
J snapshot(Paths&x,long t){auto z=x.st[t],old=x.st[t-1];long j=t-1,a=x.alpha[t],b=x.beta[t];Z pa=x.k.head(j)*old.Ma-x.s*old.Wa,pb=x.k.head(j)*old.Mb-x.s*old.Wb,diag=x.k.diagonal(j);Z self=2*b*pb+b*b*diag,cross=-2*(a*pb+b*pa+a*b*diag),inherit=-(2*a*pa+a*a*diag);need(self+cross+inherit==x.E[t]-x.E[t-1],"Retained exact causal increment");J r={{"s",x.s},{"t",t},{"n",x.s+t-1},{"alpha",a},{"beta",b},{"odd_child",x.gamma[t]},{"odd_child_n",2*(x.s+t-1)+1},{"state_signature",x.sig[t]},{"E",str(x.value(x.E[t]))},{"delta_E",str(x.value(Z(x.E[t]-x.E[t-1])))},{"forcing_self_delta",str(x.value(self))},{"forcing_cross_delta",str(x.value(cross))},{"inherited_delta",str(x.value(inherit))}};r["certificate"]=certificate(x,t,4);auto actual=x.future(t,std::min(4L,x.s-t));need(parse(actual["overshoot"])<=parse(r["certificate"]["overshoot_bound"])&&parse(actual["drift"])>=parse(r["certificate"]["drift_lower"])&&parse(actual["drift"])<=parse(r["certificate"]["drift_upper"]),"Actual signed suffix inside current-state support certificate");r["actual_short_future"]=actual;return r;}
J evaluate(const J&p){long s=p.at("s");need(s==512||s==2048||s==4096,"Frozen evaluation scales");Paths x(s);auto model=reference(p.at("model"));need(model["calibration_scale"]==512&&model["last_label_stop"]==256&&!model["held_out_used_for_fitting"].get<bool>(),"Frozen fitting boundary");J stats=J::object(),focus=J::array();for(long h:{8,32,64})stats[std::to_string(h)]={{"matched",0},{"unmatched",0},{"overshoot_failures",0},{"drift_failures",0},{"global_overshoot_failures",0},{"first_overshoot_failure",nullptr}};
 long begin=s==512?257:1;for(long t=begin;t<s;++t)for(long h:{8,32,64}){if(t+h>s)continue;auto&st=stats[std::to_string(h)];auto y=x.future(t,h);if(parse(y["overshoot"])>parse(model["unconditional_calibration"][std::to_string(h)]["overshoot_bound"]))st["global_overshoot_failures"]=st["global_overshoot_failures"].get<long>()+1;if(!model["groups"].contains(x.sig[t])){st["unmatched"]=st["unmatched"].get<long>()+1;continue;}st["matched"]=st["matched"].get<long>()+1;auto rule=model["groups"][x.sig[t]]["horizons"][std::to_string(h)];if(parse(y["overshoot"])>parse(rule["overshoot_bound"])){st["overshoot_failures"]=st["overshoot_failures"].get<long>()+1;if(st["first_overshoot_failure"].is_null())st["first_overshoot_failure"]={{"s",s},{"t",t},{"signature",x.sig[t]},{"bound",rule["overshoot_bound"]},{"actual",y}};}if(parse(y["drift"])<parse(rule["drift_lower"])||parse(y["drift"])>parse(rule["drift_upper"]))st["drift_failures"]=st["drift_failures"].get<long>()+1;}
 std::set<long>points;if(s==4096)for(long t:{227,790,1071,1073,1074,1075,1076,1077,1130,4094,4095})points.insert(t);if(s==2048)for(long t:{512,1024,1536})points.insert(t);if(p.contains("selections")){auto selected=reference(p["selections"]);for(auto row:selected["points"])if(row["s"]==s&&row["t"].get<long>()<s)points.insert(row["t"].get<long>());}
 for(long t:points){auto r=snapshot(x,t);r["forecasts"]=J::array();for(long h:{8,32,64}){if(t+h>s){r["forecasts"].push_back({{"horizon",h},{"status","RIGHT_CENSORED"}});continue;}auto actual=x.future(t,h);J y={{"horizon",h},{"actual",actual},{"rule_status","UNMATCHED"}};if(model["groups"].contains(x.sig[t])){y["rule_status"]="MATCHED";y["frozen_rule"]=model["groups"][x.sig[t]]["horizons"][std::to_string(h)];y["calibration_count"]=model["groups"][x.sig[t]]["count"];}r["forecasts"].push_back(y);}
  long matches=0,keeps=0;J counter=nullptr;for(long j=1;j<s;++j)if(j!=t&&x.sig[j]==x.sig[t]){++matches;auto c=certificate(x,j,4);if(c["preserves_C1"].get<bool>())++keeps;else if(counter.is_null())counter={{"t",j},{"certificate",c}};}r["same_state_recurrences"]={{"other_matches",matches},{"C1_certified_next_up_to4",keeps},{"first_uncertified",counter}};focus.push_back(r);}
 return {{"schema","RH_SOURCE_STATE_FORECAST_EVALUATION_R1"},{"s",s},{"evaluation_begin",begin},{"frozen_model",p["model"]},{"horizon_stats",stats},{"focus",focus},{"fitting_performed",false},{"whole_4096_held_out",true},{"scope","Empirical rules tested without refitting; separate exact finite-horizon support certificates; original E unchanged"}};
}
int main(){try{J input;std::cin>>input;auto req=input.at(0),p=req.at("payload");auto contract=reference(p.at("contract"));need(contract["id"]=="RH-FORCING-PROSPECTIVE-R1","Unchanged target and forecast boundary");J r;if(req["op"]=="RH_FORCING_STATE_CALIBRATE_R1")r=calibrate();else if(req["op"]=="RH_FORCING_STATE_EVALUATE_R1")r=evaluate(p);else throw std::runtime_error("Unknown prospective forcing operation");r["contract_sha256"]=p["contract"]["sha256"];std::cout<<J({{"ok",true},{"result",r}}).dump()<<std::endl;}catch(const std::exception&e){std::cout<<J({{"ok",false},{"error",e.what()}}).dump()<<std::endl;return 1;}}
